// Imports
import Link from "next/link"; // Routing
import { useRouter } from "next/router"; // Routing
import { default as HTMLHead } from "next/head"; // Meta
import styles from "@styles/components/Layout.module.scss"; // Styles
import {Navigation} from './Navigation';

// Types
import type { ReactElement } from "react";

export default function Layout({
  children,
}: {
  children: ReactElement | ReactElement[];
}) {
  return (
    <div>
      {/* Meta */}
      <Head />
      {/* Top header */}
      <Header />

      {/* Page content */}
      <div className={styles.content}>{children}</div>
      {/* Bottom footer */}
      <Footer />
    </div>
  );
}

/**
 * Meta HTML Head
 * @returns {ReactElement} HTML Head component
 */
function Head(): ReactElement {
  return (
    <HTMLHead>
      {/* Primary Meta Tags */}
      <title>Mu::ses</title>
      <meta name="title" content="mu::ses" />
      <meta
        name="description"
        content="Mu::ses is a collection of 300 unique melodies, generated by AI, serialized in text format, and stored on the Polygon blockchain."
      />

      {/* OG + Faceook */}
      <meta property="og:type" content="website" />
      <meta property="og:url" content="https://www.lootproject.com/" />
      <meta property="og:title" content="Mu::ses" />
      <meta
        property="og:description"
        content="Mu::ses is a collection of 300 unique melodies, generated by AI, serialized in text format, and stored on the Polygon blockchain."
      />
      <meta property="og:image" content="https://lootproject.com/meta.png" />

      {/* Twitter */}
      <meta property="twitter:card" content="summary_large_image" />
      <meta property="twitter:url" content="https://www.lootproject.com/" />
      <meta property="twitter:title" content="Mu::ses" />
      <meta
        property="twitter:description"
        content="Mu::ses is a collection of 300 unique melodies, generated by AI, serialized in text format, and stored on the Polygon blockchain."
      />
      <meta property="twitter:image" content="https://lootproject.com/meta.png" />

      {/* Font */}
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
      {/* eslint-disable-next-line @next/next/no-page-custom-font */}
      <link
        href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;700&display=swap"
        rel="stylesheet"
      />
    </HTMLHead>
  );
}

/**
 * Header
 * @returns {ReactElement} Header
 */
function Header() {
  // Collect current path for active links
  const { pathname } = useRouter();

  // Quicklinks to render
  const quicklinks: Record<string, string>[] = [
    { name: "FAQ", url: "/faq" },
    { name: "Download MIDI", url: "https://colab.research.google.com/drive/1mAeuoHXgZZ6CdY7rEBIOAmkZIjdjDkSP?usp=sharing"},
    { name: "Opensea", url: "https://opensea.io/collection/lootproject" },
  ];

  return (
      <Navigation />
  );
}

/**
 * Footer component
 * @returns {ReactElement} Footer
 */
function Footer(): ReactElement {
  return (
    <div className={styles.footer}>
      <br/>
      <p>Thanks to Loot project for the inspiration ❤️</p> 
      <p>
        This website is{" "}
        <a
          href="https://github.com/musesrecord/muses_website"
          target="_blank"
          rel="noopener noreferrer"
        >
          open-source
        </a>
        .
      </p>
    </div>
  );
}
