// Imports
import React from 'react';
import Link from "next/link"; // Local routing
import Layout from "@components/Layout"; // Layout wrapper
import styles from "@styles/pages/Home.module.scss"; // Styles
import Example1 from '../public/examples/ex1';
import Example2 from '../public/examples/ex2';
import Example3 from '../public/examples/ex3';
import ReactAudioPlayer from 'react-audio-player';

// Types
import type { ReactElement } from "react";

export default function Home(): ReactElement {
  // Quicklinks to render
  const quicklinks: Record<string, string>[] = [
    { name: "ra::dio", url: "/radio" },
    {
      name: "j::am",
      url: "/jam",
    },
    {
      name: "fes::tival",
      url: "/festival",
    },
  ];

  return (
    <Layout>
      <div>
        <div className={styles.home__cta}>
          {/* CTA title */}
          <h1>mu::ses</h1>

          {/* Quicklinks */}
          <ul>
            {quicklinks.map(({ name, url }, i) => {
              return (
                <li key={i}>
                  {url.startsWith("/") ? (
                    // If link to local page use Link
                    <Link href={url}>
                      <a>{name}</a>
                    </Link>
                  ) : (
                    // Else, redirect in new tab
                    <a href={url} target="_blank" rel="noopener noreferrer">
                      {name}
                    </a>
                  )}
                </li>
              );
            })}
          </ul>

          {/* CTA Description */}
          <p>
            A collection of melodies generated by AI, serialized to a text format, and stored on-chain. 
            <br/> Feel free to use compositions in any way you want. Royalty-Free. Be creative!
          </p>
        </div>

        {/* Rendering of muses samples */}
        <div className={styles.home__preview}>
          <span>Preview of some melodies in audio format:</span>
            <div className={styles.home__preview__section}>
              <div className={styles.home__preview__muse}>
                <span>#0208</span>
                <ReactAudioPlayer
                    preload="none"
                    src="https://gateway.pinata.cloud/ipfs/Qmcw6KCjWacarAudrZtrmb4cs2PgK31XuGhkY2f2HPrFMi"
                    controls
                  />
                  <Example1 />
              </div>
            </div>
            <div className={styles.home__preview__section} >
              <div className={styles.home__preview__muse}>
                <span>#0216</span>
                <ReactAudioPlayer
                    preload="none"
                    src="https://gateway.pinata.cloud/ipfs/QmbSUcDFrkVrYQQoPeEZ3BX4LAXJLexTjo3R9vNUJkyFVq"
                    controls
                  />
                  <Example2 />
              </div>
            </div>
            <div className={styles.home__preview__section} >
              <div className={styles.home__preview__muse}>
                <span>#0181</span>
                <ReactAudioPlayer
                    preload="none"
                    src="https://gateway.pinata.cloud/ipfs/Qmb2FT4bSeEVZHgQATP6y5PnEUpxrffRTyGQE5cHfKEevN"
                    controls
                  />
                  <Example3 />
              </div>
            </div>
        </div>

      </div>
    </Layout>
  );
}
